version: '3.4'

services:
  docker.randomgenerator.webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  docker.randomgenerator.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

